### PR TITLE
Support for THREE r118

### PR DESCRIPTION
**Pull request by squarefeet**

### CODE REVIEW

**Comment by squarefeet** [comment]
@titansoftime Would you mind having a quick look over this if you have time?

**Comment by RemusMar** [comment]
Luke,

You can find the fix here: https://github.com/RemusMar/ShaderParticleEngine

**Comment by titansoftime** [comment]
This looks good to me. Thanks!

**Comment by squarefeet** [comment]
Thanks both. Will merge this.

**Pull request merged**
